### ISSUE TITLE
Variable font in WOFF2

### ISSUE THREAD

**Issue by leoshortik** [canonical/Ubuntu-Sans-fonts#122]
Hi,
can you make a woff2 variable font?
Thx
Shortik

**Comment by djrrb** [comment]
Hi Shortik, you can find that [here](https://github.com/canonical/Ubuntu-Sans-fonts/blob/main/fonts/webfont/UbuntuSans%5Bwdth%2Cwght%5D.woff2) as well as in the release packages. Hope that helps, and feel free to reopen if that didn’t address your issue.
