### ISSUE TITLE
Monospace font is missing

### ISSUE THREAD

**Issue by ClementChaumel** [canonical/Ubuntu-Sans-fonts#52]
I can't find the monospace version of the font on the repo. Does it exist and if yes, where can I find it?
Thanks!

**Comment by sergeevabc** [comment]
What is the difference between
`UbuntuMono-fonts-fonts.zip`
and
`UbuntuSansMono-fonts-v1.004.zip`?

**Comment by djrrb** [comment]
@sergeevabc Sorry about that...looks like the two zips have duplicate fonts. The first zip is larger because it also contains the QA files. I have removed it from the release.

**Comment by sergeevabc** [comment]
@djrrb, it seems you forgot to remove `UbuntuMono-fonts-fonts.zip` [here](https://github.com/canonical/Ubuntu-Sans-Mono-fonts/releases/tag/v1.004).

**Comment by djrrb** [comment]
@sergeevabc Thank you! 🙈
